/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#pragma once
#include <vector>
#include <map>
#include <sstream>
#include <string>
#include "IfcPPBasicTypes.h"
#include "IfcPPObject.h"
#include "IfcPPGlobal.h"

// TYPE IfcSubContractResourceTypeEnum = ENUMERATION OF	(PURCHASE	,WORK	,USERDEFINED	,NOTDEFINED);
class IFCPP_EXPORT IfcSubContractResourceTypeEnum : virtual public IfcPPObject
{
public:
	enum IfcSubContractResourceTypeEnumEnum
	{
		ENUM_PURCHASE,
		ENUM_WORK,
		ENUM_USERDEFINED,
		ENUM_NOTDEFINED
	};

	IfcSubContractResourceTypeEnum();
	IfcSubContractResourceTypeEnum( IfcSubContractResourceTypeEnumEnum e ) { m_enum = e; }
	~IfcSubContractResourceTypeEnum();
	virtual const char* className() const { return "IfcSubContractResourceTypeEnum"; }
	virtual shared_ptr<IfcPPObject> getDeepCopy( IfcPPCopyOptions& options );
	virtual void getStepParameter( std::stringstream& stream, bool is_select_type = false ) const;
	virtual const std::wstring toString() const;
	static shared_ptr<IfcSubContractResourceTypeEnum> createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map );
	IfcSubContractResourceTypeEnumEnum m_enum;
};

