/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcActorSelect.h"

// TYPE IfcActorSelect = SELECT	(IfcOrganization	,IfcPerson	,IfcPersonAndOrganization);
shared_ptr<IfcActorSelect> IfcActorSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcActorSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcActorSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcActorSelect>();
	}
	shared_ptr<IfcActorSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
