/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcAxis2Placement.h"

// TYPE IfcAxis2Placement = SELECT	(IfcAxis2Placement2D	,IfcAxis2Placement3D);
shared_ptr<IfcAxis2Placement> IfcAxis2Placement::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcAxis2Placement>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcAxis2Placement>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcAxis2Placement>();
	}
	shared_ptr<IfcAxis2Placement> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
