/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcNormalisedRatioMeasure.h"
#include "IFC4/include/IfcColourOrFactor.h"

// TYPE IfcColourOrFactor = SELECT	(IfcColourRgb	,IfcNormalisedRatioMeasure);
shared_ptr<IfcColourOrFactor> IfcColourOrFactor::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcColourOrFactor>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcColourOrFactor>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcColourOrFactor>();
	}
	shared_ptr<IfcColourOrFactor> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
