/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcCsgSelect.h"

// TYPE IfcCsgSelect = SELECT	(IfcBooleanResult	,IfcCsgPrimitive3D);
shared_ptr<IfcCsgSelect> IfcCsgSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcCsgSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcCsgSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcCsgSelect>();
	}
	shared_ptr<IfcCsgSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
