/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcClassificationSelect.h"

// TYPE IfcClassificationSelect = SELECT	(IfcClassification	,IfcClassificationReference);
shared_ptr<IfcClassificationSelect> IfcClassificationSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcClassificationSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcClassificationSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcClassificationSelect>();
	}
	shared_ptr<IfcClassificationSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
