/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcCurveStyleFontSelect.h"
#include "IFC4/include/IfcCurveFontOrScaledCurveFontSelect.h"

// TYPE IfcCurveFontOrScaledCurveFontSelect = SELECT	(IfcCurveStyleFontAndScaling	,IfcCurveStyleFontSelect);
shared_ptr<IfcCurveFontOrScaledCurveFontSelect> IfcCurveFontOrScaledCurveFontSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcCurveFontOrScaledCurveFontSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcCurveFontOrScaledCurveFontSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcCurveFontOrScaledCurveFontSelect>();
	}
	shared_ptr<IfcCurveFontOrScaledCurveFontSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
