/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcCurveOnSurface.h"

// TYPE IfcCurveOnSurface = SELECT	(IfcCompositeCurveOnSurface	,IfcPcurve	,IfcSurfaceCurve);
shared_ptr<IfcCurveOnSurface> IfcCurveOnSurface::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcCurveOnSurface>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcCurveOnSurface>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcCurveOnSurface>();
	}
	shared_ptr<IfcCurveOnSurface> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
