/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcCoordinateReferenceSystemSelect.h"

// TYPE IfcCoordinateReferenceSystemSelect = SELECT	(IfcCoordinateReferenceSystem	,IfcGeometricRepresentationContext);
shared_ptr<IfcCoordinateReferenceSystemSelect> IfcCoordinateReferenceSystemSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcCoordinateReferenceSystemSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcCoordinateReferenceSystemSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcCoordinateReferenceSystemSelect>();
	}
	shared_ptr<IfcCoordinateReferenceSystemSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
