/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcCurveFontOrScaledCurveFontSelect.h"
#include "IFC4/include/IfcCurveStyleFontSelect.h"

// TYPE IfcCurveStyleFontSelect = SELECT	(IfcCurveStyleFont	,IfcPreDefinedCurveFont);
shared_ptr<IfcCurveStyleFontSelect> IfcCurveStyleFontSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcCurveStyleFontSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcCurveStyleFontSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcCurveStyleFontSelect>();
	}
	shared_ptr<IfcCurveStyleFontSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
