/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcCurveOrEdgeCurve.h"

// TYPE IfcCurveOrEdgeCurve = SELECT	(IfcBoundedCurve	,IfcEdgeCurve);
shared_ptr<IfcCurveOrEdgeCurve> IfcCurveOrEdgeCurve::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcCurveOrEdgeCurve>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcCurveOrEdgeCurve>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcCurveOrEdgeCurve>();
	}
	shared_ptr<IfcCurveOrEdgeCurve> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
