/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDayInWeekNumber.h"

// TYPE IfcDayInWeekNumber = INTEGER;
IfcDayInWeekNumber::IfcDayInWeekNumber() {}
IfcDayInWeekNumber::IfcDayInWeekNumber( int value ) { m_value = value; }
IfcDayInWeekNumber::~IfcDayInWeekNumber() {}
shared_ptr<IfcPPObject> IfcDayInWeekNumber::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcDayInWeekNumber> copy_self( new IfcDayInWeekNumber() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcDayInWeekNumber::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCDAYINWEEKNUMBER("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcDayInWeekNumber::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcDayInWeekNumber> IfcDayInWeekNumber::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcDayInWeekNumber>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcDayInWeekNumber>(); }
	shared_ptr<IfcDayInWeekNumber> type_object( new IfcDayInWeekNumber() );
	readInt( arg, type_object->m_value );
	return type_object;
}
