/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDerivedMeasureValue.h"
#include "IFC4/include/IfcDoseEquivalentMeasure.h"

// TYPE IfcDoseEquivalentMeasure = REAL;
IfcDoseEquivalentMeasure::IfcDoseEquivalentMeasure() {}
IfcDoseEquivalentMeasure::IfcDoseEquivalentMeasure( double value ) { m_value = value; }
IfcDoseEquivalentMeasure::~IfcDoseEquivalentMeasure() {}
shared_ptr<IfcPPObject> IfcDoseEquivalentMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcDoseEquivalentMeasure> copy_self( new IfcDoseEquivalentMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcDoseEquivalentMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCDOSEEQUIVALENTMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcDoseEquivalentMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcDoseEquivalentMeasure> IfcDoseEquivalentMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcDoseEquivalentMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcDoseEquivalentMeasure>(); }
	shared_ptr<IfcDoseEquivalentMeasure> type_object( new IfcDoseEquivalentMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
