/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDerivedMeasureValue.h"
#include "IFC4/include/IfcFrequencyMeasure.h"

// TYPE IfcFrequencyMeasure = REAL;
IfcFrequencyMeasure::IfcFrequencyMeasure() {}
IfcFrequencyMeasure::IfcFrequencyMeasure( double value ) { m_value = value; }
IfcFrequencyMeasure::~IfcFrequencyMeasure() {}
shared_ptr<IfcPPObject> IfcFrequencyMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcFrequencyMeasure> copy_self( new IfcFrequencyMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcFrequencyMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCFREQUENCYMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcFrequencyMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcFrequencyMeasure> IfcFrequencyMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcFrequencyMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcFrequencyMeasure>(); }
	shared_ptr<IfcFrequencyMeasure> type_object( new IfcFrequencyMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
