/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcGeometricSetSelect.h"

// TYPE IfcGeometricSetSelect = SELECT	(IfcCurve	,IfcPoint	,IfcSurface);
shared_ptr<IfcGeometricSetSelect> IfcGeometricSetSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcGeometricSetSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcGeometricSetSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcGeometricSetSelect>();
	}
	shared_ptr<IfcGeometricSetSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
