/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDerivedMeasureValue.h"
#include "IFC4/include/IfcIsothermalMoistureCapacityMeasure.h"

// TYPE IfcIsothermalMoistureCapacityMeasure = REAL;
IfcIsothermalMoistureCapacityMeasure::IfcIsothermalMoistureCapacityMeasure() {}
IfcIsothermalMoistureCapacityMeasure::IfcIsothermalMoistureCapacityMeasure( double value ) { m_value = value; }
IfcIsothermalMoistureCapacityMeasure::~IfcIsothermalMoistureCapacityMeasure() {}
shared_ptr<IfcPPObject> IfcIsothermalMoistureCapacityMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcIsothermalMoistureCapacityMeasure> copy_self( new IfcIsothermalMoistureCapacityMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcIsothermalMoistureCapacityMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCISOTHERMALMOISTURECAPACITYMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcIsothermalMoistureCapacityMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcIsothermalMoistureCapacityMeasure> IfcIsothermalMoistureCapacityMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcIsothermalMoistureCapacityMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcIsothermalMoistureCapacityMeasure>(); }
	shared_ptr<IfcIsothermalMoistureCapacityMeasure> type_object( new IfcIsothermalMoistureCapacityMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
