/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcLightDistributionDataSourceSelect.h"

// TYPE IfcLightDistributionDataSourceSelect = SELECT	(IfcExternalReference	,IfcLightIntensityDistribution);
shared_ptr<IfcLightDistributionDataSourceSelect> IfcLightDistributionDataSourceSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcLightDistributionDataSourceSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcLightDistributionDataSourceSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcLightDistributionDataSourceSelect>();
	}
	shared_ptr<IfcLightDistributionDataSourceSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
