/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcLibrarySelect.h"

// TYPE IfcLibrarySelect = SELECT	(IfcLibraryInformation	,IfcLibraryReference);
shared_ptr<IfcLibrarySelect> IfcLibrarySelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcLibrarySelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcLibrarySelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcLibrarySelect>();
	}
	shared_ptr<IfcLibrarySelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
