/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDerivedMeasureValue.h"
#include "IFC4/include/IfcLinearVelocityMeasure.h"

// TYPE IfcLinearVelocityMeasure = REAL;
IfcLinearVelocityMeasure::IfcLinearVelocityMeasure() {}
IfcLinearVelocityMeasure::IfcLinearVelocityMeasure( double value ) { m_value = value; }
IfcLinearVelocityMeasure::~IfcLinearVelocityMeasure() {}
shared_ptr<IfcPPObject> IfcLinearVelocityMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcLinearVelocityMeasure> copy_self( new IfcLinearVelocityMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcLinearVelocityMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCLINEARVELOCITYMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcLinearVelocityMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcLinearVelocityMeasure> IfcLinearVelocityMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcLinearVelocityMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcLinearVelocityMeasure>(); }
	shared_ptr<IfcLinearVelocityMeasure> type_object( new IfcLinearVelocityMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
