/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcLayeredItem.h"

// TYPE IfcLayeredItem = SELECT	(IfcRepresentation	,IfcRepresentationItem);
shared_ptr<IfcLayeredItem> IfcLayeredItem::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcLayeredItem>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcLayeredItem>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcLayeredItem>();
	}
	shared_ptr<IfcLayeredItem> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
