/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcMaterialSelect.h"

// TYPE IfcMaterialSelect = SELECT	(IfcMaterialDefinition	,IfcMaterialList	,IfcMaterialUsageDefinition);
shared_ptr<IfcMaterialSelect> IfcMaterialSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcMaterialSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcMaterialSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcMaterialSelect>();
	}
	shared_ptr<IfcMaterialSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
