/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcColourOrFactor.h"
#include "IFC4/include/IfcMeasureValue.h"
#include "IFC4/include/IfcSizeSelect.h"
#include "IFC4/include/IfcNormalisedRatioMeasure.h"

// TYPE IfcNormalisedRatioMeasure = IfcRatioMeasure;
IfcNormalisedRatioMeasure::IfcNormalisedRatioMeasure() {}
IfcNormalisedRatioMeasure::~IfcNormalisedRatioMeasure() {}
shared_ptr<IfcPPObject> IfcNormalisedRatioMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcNormalisedRatioMeasure> copy_self( new IfcNormalisedRatioMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcNormalisedRatioMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCNORMALISEDRATIOMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcNormalisedRatioMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcNormalisedRatioMeasure> IfcNormalisedRatioMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcNormalisedRatioMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcNormalisedRatioMeasure>(); }
	shared_ptr<IfcNormalisedRatioMeasure> type_object( new IfcNormalisedRatioMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
