/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcProductSelect.h"

// TYPE IfcProductSelect = SELECT	(IfcProduct	,IfcTypeProduct);
shared_ptr<IfcProductSelect> IfcProductSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcProductSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcProductSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcProductSelect>();
	}
	shared_ptr<IfcProductSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
