/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcProductRepresentationSelect.h"

// TYPE IfcProductRepresentationSelect = SELECT	(IfcProductDefinitionShape	,IfcRepresentationMap);
shared_ptr<IfcProductRepresentationSelect> IfcProductRepresentationSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcProductRepresentationSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcProductRepresentationSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcProductRepresentationSelect>();
	}
	shared_ptr<IfcProductRepresentationSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
