/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcProcessSelect.h"

// TYPE IfcProcessSelect = SELECT	(IfcProcess	,IfcTypeProcess);
shared_ptr<IfcProcessSelect> IfcProcessSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcProcessSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcProcessSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcProcessSelect>();
	}
	shared_ptr<IfcProcessSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
