/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcPointOrVertexPoint.h"

// TYPE IfcPointOrVertexPoint = SELECT	(IfcPoint	,IfcVertexPoint);
shared_ptr<IfcPointOrVertexPoint> IfcPointOrVertexPoint::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcPointOrVertexPoint>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcPointOrVertexPoint>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcPointOrVertexPoint>();
	}
	shared_ptr<IfcPointOrVertexPoint> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
