/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcPropertySetDefinitionSet.h"
#include "IFC4/include/IfcPropertySetDefinitionSelect.h"

// TYPE IfcPropertySetDefinitionSelect = SELECT	(IfcPropertySetDefinition	,IfcPropertySetDefinitionSet);
shared_ptr<IfcPropertySetDefinitionSelect> IfcPropertySetDefinitionSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcPropertySetDefinitionSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcPropertySetDefinitionSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcPropertySetDefinitionSelect>();
	}
	shared_ptr<IfcPropertySetDefinitionSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
