/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDerivedMeasureValue.h"
#include "IFC4/include/IfcPHMeasure.h"

// TYPE IfcPHMeasure = REAL;
IfcPHMeasure::IfcPHMeasure() {}
IfcPHMeasure::IfcPHMeasure( double value ) { m_value = value; }
IfcPHMeasure::~IfcPHMeasure() {}
shared_ptr<IfcPPObject> IfcPHMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcPHMeasure> copy_self( new IfcPHMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcPHMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCPHMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcPHMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcPHMeasure> IfcPHMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcPHMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcPHMeasure>(); }
	shared_ptr<IfcPHMeasure> type_object( new IfcPHMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
