/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcNullStyle.h"
#include "IFC4/include/IfcPresentationStyleSelect.h"

// TYPE IfcPresentationStyleSelect = SELECT	(IfcCurveStyle	,IfcFillAreaStyle	,IfcNullStyle	,IfcSurfaceStyle	,IfcTextStyle);
shared_ptr<IfcPresentationStyleSelect> IfcPresentationStyleSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcPresentationStyleSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcPresentationStyleSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcPresentationStyleSelect>();
	}
	shared_ptr<IfcPresentationStyleSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
