/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDerivedMeasureValue.h"
#include "IFC4/include/IfcRotationalFrequencyMeasure.h"

// TYPE IfcRotationalFrequencyMeasure = REAL;
IfcRotationalFrequencyMeasure::IfcRotationalFrequencyMeasure() {}
IfcRotationalFrequencyMeasure::IfcRotationalFrequencyMeasure( double value ) { m_value = value; }
IfcRotationalFrequencyMeasure::~IfcRotationalFrequencyMeasure() {}
shared_ptr<IfcPPObject> IfcRotationalFrequencyMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcRotationalFrequencyMeasure> copy_self( new IfcRotationalFrequencyMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcRotationalFrequencyMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCROTATIONALFREQUENCYMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcRotationalFrequencyMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcRotationalFrequencyMeasure> IfcRotationalFrequencyMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcRotationalFrequencyMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcRotationalFrequencyMeasure>(); }
	shared_ptr<IfcRotationalFrequencyMeasure> type_object( new IfcRotationalFrequencyMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
