/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcArcIndex.h"
#include "IFC4/include/IfcLineIndex.h"
#include "IFC4/include/IfcSegmentIndexSelect.h"

// TYPE IfcSegmentIndexSelect = SELECT	(IfcArcIndex	,IfcLineIndex);
shared_ptr<IfcSegmentIndexSelect> IfcSegmentIndexSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcSegmentIndexSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcSegmentIndexSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcSegmentIndexSelect>();
	}
	shared_ptr<IfcSegmentIndexSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
