/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcShell.h"

// TYPE IfcShell = SELECT	(IfcClosedShell	,IfcOpenShell);
shared_ptr<IfcShell> IfcShell::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcShell>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcShell>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcShell>();
	}
	shared_ptr<IfcShell> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
