/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcSurfaceOrFaceSurface.h"

// TYPE IfcSurfaceOrFaceSurface = SELECT	(IfcFaceBasedSurfaceModel	,IfcFaceSurface	,IfcSurface);
shared_ptr<IfcSurfaceOrFaceSurface> IfcSurfaceOrFaceSurface::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcSurfaceOrFaceSurface>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcSurfaceOrFaceSurface>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcSurfaceOrFaceSurface>();
	}
	shared_ptr<IfcSurfaceOrFaceSurface> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
