/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcBinary.h"
#include "IFC4/include/IfcBoolean.h"
#include "IFC4/include/IfcDate.h"
#include "IFC4/include/IfcDateTime.h"
#include "IFC4/include/IfcDuration.h"
#include "IFC4/include/IfcIdentifier.h"
#include "IFC4/include/IfcInteger.h"
#include "IFC4/include/IfcLabel.h"
#include "IFC4/include/IfcLogical.h"
#include "IFC4/include/IfcPositiveInteger.h"
#include "IFC4/include/IfcReal.h"
#include "IFC4/include/IfcText.h"
#include "IFC4/include/IfcTime.h"
#include "IFC4/include/IfcTimeStamp.h"
#include "IFC4/include/IfcValue.h"
#include "IFC4/include/IfcSimpleValue.h"

// TYPE IfcSimpleValue = SELECT	(IfcBinary	,IfcBoolean	,IfcDate	,IfcDateTime	,IfcDuration	,IfcIdentifier	,IfcInteger	,IfcLabel	,IfcLogical	,IfcPositiveInteger	,IfcReal	,IfcText	,IfcTime	,IfcTimeStamp);
shared_ptr<IfcSimpleValue> IfcSimpleValue::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcSimpleValue>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcSimpleValue>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcSimpleValue>();
	}
	shared_ptr<IfcSimpleValue> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
