/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcSpecularExponent.h"
#include "IFC4/include/IfcSpecularRoughness.h"
#include "IFC4/include/IfcSpecularHighlightSelect.h"

// TYPE IfcSpecularHighlightSelect = SELECT	(IfcSpecularExponent	,IfcSpecularRoughness);
shared_ptr<IfcSpecularHighlightSelect> IfcSpecularHighlightSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcSpecularHighlightSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcSpecularHighlightSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcSpecularHighlightSelect>();
	}
	shared_ptr<IfcSpecularHighlightSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
