/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDerivedMeasureValue.h"
#include "IFC4/include/IfcTorqueMeasure.h"

// TYPE IfcTorqueMeasure = REAL;
IfcTorqueMeasure::IfcTorqueMeasure() {}
IfcTorqueMeasure::IfcTorqueMeasure( double value ) { m_value = value; }
IfcTorqueMeasure::~IfcTorqueMeasure() {}
shared_ptr<IfcPPObject> IfcTorqueMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcTorqueMeasure> copy_self( new IfcTorqueMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcTorqueMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCTORQUEMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcTorqueMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcTorqueMeasure> IfcTorqueMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcTorqueMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcTorqueMeasure>(); }
	shared_ptr<IfcTorqueMeasure> type_object( new IfcTorqueMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
