/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */

#include <sstream>
#include <limits>
#include <map>
#include "reader/ReaderUtil.h"
#include "writer/WriterUtil.h"
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "IFC4/include/IfcDerivedMeasureValue.h"
#include "IFC4/include/IfcThermalConductivityMeasure.h"

// TYPE IfcThermalConductivityMeasure = REAL;
IfcThermalConductivityMeasure::IfcThermalConductivityMeasure() {}
IfcThermalConductivityMeasure::IfcThermalConductivityMeasure( double value ) { m_value = value; }
IfcThermalConductivityMeasure::~IfcThermalConductivityMeasure() {}
shared_ptr<IfcPPObject> IfcThermalConductivityMeasure::getDeepCopy( IfcPPCopyOptions& options )
{
	shared_ptr<IfcThermalConductivityMeasure> copy_self( new IfcThermalConductivityMeasure() );
	copy_self->m_value = m_value;
	return copy_self;
}
void IfcThermalConductivityMeasure::getStepParameter( std::stringstream& stream, bool is_select_type ) const
{
	if( is_select_type ) { stream << "IFCTHERMALCONDUCTIVITYMEASURE("; }
	stream << m_value;
	if( is_select_type ) { stream << ")"; }
}
const std::wstring IfcThermalConductivityMeasure::toString() const
{
	std::wstringstream strs;
	strs << m_value;
	return strs.str();
}
shared_ptr<IfcThermalConductivityMeasure> IfcThermalConductivityMeasure::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.compare( L"$" ) == 0 ) { return shared_ptr<IfcThermalConductivityMeasure>(); }
	else if( arg.compare( L"*" ) == 0 ) { return shared_ptr<IfcThermalConductivityMeasure>(); }
	shared_ptr<IfcThermalConductivityMeasure> type_object( new IfcThermalConductivityMeasure() );
	readReal( arg, type_object->m_value );
	return type_object;
}
