/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcParameterValue.h"
#include "IFC4/include/IfcTrimmingSelect.h"

// TYPE IfcTrimmingSelect = SELECT	(IfcCartesianPoint	,IfcParameterValue);
shared_ptr<IfcTrimmingSelect> IfcTrimmingSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcTrimmingSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcTrimmingSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcTrimmingSelect>();
	}
	shared_ptr<IfcTrimmingSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
