/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcVectorOrDirection.h"

// TYPE IfcVectorOrDirection = SELECT	(IfcDirection	,IfcVector);
shared_ptr<IfcVectorOrDirection> IfcVectorOrDirection::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcVectorOrDirection>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcVectorOrDirection>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcVectorOrDirection>();
	}
	shared_ptr<IfcVectorOrDirection> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
