/* Code generated by IfcQuery EXPRESS generator, www.ifcquery.com */
#include <map>
#include "model/IfcPPBasicTypes.h"
#include "model/IfcPPException.h"
#include "reader/ReaderUtil.h"
#include "IFC4/include/IfcBoolean.h"
#include "IFC4/include/IfcWarpingMomentMeasure.h"
#include "IFC4/include/IfcWarpingStiffnessSelect.h"

// TYPE IfcWarpingStiffnessSelect = SELECT	(IfcBoolean	,IfcWarpingMomentMeasure);
shared_ptr<IfcWarpingStiffnessSelect> IfcWarpingStiffnessSelect::createObjectFromSTEP( const std::wstring& arg, const std::map<int,shared_ptr<IfcPPEntity> >& map )
{
	if( arg.size() == 0 ){ return shared_ptr<IfcWarpingStiffnessSelect>(); }
	if( arg.compare(L"$")==0 )
	{
		return shared_ptr<IfcWarpingStiffnessSelect>();
	}
	if( arg.compare(L"*")==0 )
	{
		return shared_ptr<IfcWarpingStiffnessSelect>();
	}
	shared_ptr<IfcWarpingStiffnessSelect> result_object;
	readSelectType( arg, result_object, map );
	return result_object;
}
